### ISSUE TITLE
Dodać wczytywanie danych motoryzacyjnych z olx-a

### ISSUE THREAD

**Issue by TinkerGlass** [IITA-DMCS-2122/iita_elixir#10]
Zaciągnąć z olx-a z kategorii motoryzacyjnej dane o samochodach,
 zaciągnąć dane do tabeli (id, marka, model, link)

**Comment by bartlomiejolczakdmcs** [comment]
Biblioteka do scrapowania - https://github.com/elixir-crawly/crawly
Biblioteka do tasków (odpalanie rzeczy w tle) - https://github.com/akira/exq

**Comment by gawronA** [comment]
Solved
