### ISSUE TITLE
Rozwiązanie problemu z połączeniem do bazy danych w trakcie wykonywania testów

### ISSUE THREAD

**Issue by krystiankowalski95** [IITA-DMCS-2122/iita_elixir#9]
`Error: 5.297 [error] GenServer #PID<0.5087.0> terminating
Warning: ** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused
(db_connection 2.4.1) lib/db_connection/connection.ex💯 DBConnection.Connection.connect/2
Warning: (connection 1.1.0) lib/connection.ex:622: Connection.enter_connect/5
(stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Warning: Last message: nil
State: Postgrex.Protocol

Error: 5.303 [error] GenServer #PID<0.5093.0> terminating
Warning: ** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused
** (Mix) The database for Todo.Repo couldn't be created: killed
(db_connection 2.4.1) lib/db_connection/connection.ex💯 DBConnection.Connection.connect/2
Warning: (connection 1.1.0) lib/connection.ex:622: Connection.enter_connect/5
(stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Warning: Last message: nil
State: Postgrex.Protocol
Error: Process completed with exit code 1.`

**Comment by pkomuda** [comment]
Konfiguracja testowa korzysta teraz z bazy danych na heroku (branch F_olx_scrapping_db)
